M48
; DRILL file {KiCad 9.0.5} date 2025-10-23T20:15:50+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-23T20:15:50+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.200
%
G90
G05
T1
X35.506Y-93.75
X41.286Y-93.75
T2
X27.914Y-44.159
T3
X27.914Y-50.509
M30
